//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod_Installer.Resources.Localization.Controls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal de_DE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mod_Installer.Resources.Localization.Controls.de-DE", typeof(de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Project Haupt Ordner.
        /// </summary>
        public static string BOTDirectory_label {
            get {
                return ResourceManager.GetString("BOTDirectory_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP Archiv(e) hinzufügen.
        /// </summary>
        public static string btnAddZipArchive {
            get {
                return ResourceManager.GetString("btnAddZipArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchsuchen.
        /// </summary>
        public static string btnBOTDirectoryBrowse {
            get {
                return ResourceManager.GetString("btnBOTDirectoryBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchsuchen.
        /// </summary>
        public static string btnDBMDirectoryBrowse {
            get {
                return ResourceManager.GetString("btnDBMDirectoryBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods installieren.
        /// </summary>
        public static string btnInstallMods {
            get {
                return ResourceManager.GetString("btnInstallMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von Liste löschen.
        /// </summary>
        public static string btnRemoveSelectedZip {
            get {
                return ResourceManager.GetString("btnRemoveSelectedZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualisiere Mods.
        /// </summary>
        public static string btnResyncMods {
            get {
                return ResourceManager.GetString("btnResyncMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Bot Maker Haupt Ordner.
        /// </summary>
        public static string DBMDirectory_label {
            get {
                return ResourceManager.GetString("DBMDirectory_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erweiterte Optionen.
        /// </summary>
        public static string gbAdvancedOptions {
            get {
                return ResourceManager.GetString("gbAdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner.
        /// </summary>
        public static string gbDirectories {
            get {
                return ResourceManager.GetString("gbDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle die Mod ZIP Datei aus (Oder ziehe sie hierher).
        /// </summary>
        public static string gbSelectedModZIPArchives {
            get {
                return ResourceManager.GetString("gbSelectedModZIPArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBM Mod Installer Log.
        /// </summary>
        public static string groupBox6 {
            get {
                return ResourceManager.GetString("groupBox6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de-DE.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBM Mod Installer.
        /// </summary>
        public static string MainForm {
            get {
                return ResourceManager.GetString("MainForm", resourceCulture);
            }
        }
    }
}
